apiVersion: apps/v1      
kind: Deployment          
metadata:                
  name: nginx-deployment      
  labels:
    app: nginx                
spec:                         
  replicas: 1             
  selector:                 
    matchLabels:     
      app: nginx
  template:
    metadata:
      labels:                 # pod의 label
        app: nginx
    spec:
      containers:             # 컨테이너 설정
      - name: nginx          
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            port: 80
            path: /test
          initialDelaySeconds: 60
        readinessProbe:
          httpGet:
            port: 80
            path: /test
          initialDelaySeconds: 60
        volumeMounts:
        - name: hostvol
          mountPath: /usr/share/nginx/html
      volumes:
      - name: hostvol
        hostPath:
          path: /home/data/nginx/html
          type: Directory
